### ISSUE TITLE
More descriptive name

### ISSUE THREAD

**Issue by asizikov** [shiftkey/octonotes#12]
Hermes is a cool name, though it's hard to say what this tool is about. 
I know naming is hard, but it worth a try. Since it's coupled to GitHub and Octokit could we try something like: 

* OctoNotes
* GitHubReleaseNotes
* RN (haha, an executable could be called `rn` with `-rf /` command line option)
* Anything else

**Comment by shiftkey** [comment]
I kind of like the brevity and succinctness of `OctoNotes` - `GitHubReleaseNotes` feels a bit too formal for my liking.

**Comment by paladique** [comment]
:+1: to OctoNotes!

**Comment by shiftkey** [comment]
aaaand renamed: https://github.com/shiftkey/octonotes
